In [5]:
import pandas as pd

FILE_PATH = '../data/'
FILE_NAME = 'telco_customer_churn_silver.csv'
df = pd.read_csv(FILE_PATH+FILE_NAME, sep=',')
df.shape

(7032, 21)

In [7]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
df.head(1)

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No

In [18]:
TARGET_COLUMN = 'Churn'
NUMERICAL_COLUMNS = ['Tenure', 'MonthlyCharges', 'TotalCharges']
CATEGORICAL_COLUMNS = []

for column in df.columns:
    if column not in NUMERICAL_COLUMNS and column != TARGET_COLUMN and column != 'CustomerID':
        CATEGORICAL_COLUMNS.append(column)

In [11]:
# TRANSFORMA Churn EM VARIÁVEL BINÁRIA
df['Churn'] = df['Churn'].replace({'Yes':'1', 'No':'0'})
df['Churn'] = df['Churn'].astype(int)
df['Churn'].dtype

dtype('int64')

## Separa os dados de treino e teste

In [16]:
from sklearn.model_selection import train_test_split

TARGET_COLUMN = 'Churn'
RANDOM_STATE = 42

X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=[TARGET_COLUMN]), # passa dados de treino sem a variável target
    df[TARGET_COLUMN], # passa a variável target
    test_size=0.25, # define o tamo dos dados de teste
    random_state=RANDOM_STATE, # fixa a semente do gerador de números aleatórios usado para embaralhar os dados antes da divisão
    stratify=df[TARGET_COLUMN] # mantém a mesma proporção das classes de y em ambos os conjuntos
)

## Encoding variáveis categoricas

In [21]:
from sklearn.preprocessing import OneHotEncoder

for column in CATEGORICAL_COLUMNS:
    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
    encoded = encoder.fit_transform(df[[column]])
    
    df_encoded = pd.DataFrame(encoded, columns=encoder.get_feature_names_out([column]))
    df = pd.concat([df.drop(columns=[column]), df_encoded], axis=1)
df.head()

,CustomerID,Tenure,MonthlyCharges,TotalCharges,Churn,Gender_Female,Gender_Male,SeniorCitizen_No,SeniorCitizen_Yes,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,PhoneService_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,1,29.85,29.85,0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,5575-GNVDE,34,56.95,1889.50,0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,3668-QPYBK,2,53.85,108.15,1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,7795-CFOCW,45,42.30,1840.75,0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4,9237-HQITU,2,70.70,151.65,1,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0